# src/phase2/__init__.py

from .schema import (
    APPROVED_MAX_P,
    APPROVED_MAX_Q,
    APPROVED_MAX_R,
    APPROVED_MAX_S,
    SCHEMA_V2_MIN_FLAT_DIM,
    FamilyId,
    MeanFamily,
    VolatilityFamily,
    ModelSpec,
    validate_order_bounds,
    validate_family_consistency,
    validate_parameter_lengths,
    validate_no_legacy_collision,
    validate_model_spec,
    is_c_family,
    is_a_family,
    is_b_family,
    schema_v2_index_map,
    to_flat_boundary_vector,
    from_flat_boundary_vector,
)

from .constraints import (
    VALIDATION_TOLERANCE,
    PERSISTENCE_TOL,
    ROOT_BOUNDARY_MARGIN,
    ConstraintResult,
    validate_ar_stationarity,
    validate_ma_invertibility,
    validate_garch_constraints,
    validate_math_constraints,
    require_math_valid,
    require_constraint_pass,
)

from .sampler import (
    GenerationRequest,
    GenerationResult,
    validate_generation_request,
    generate_model_spec,
)

from .simulator import (
    SimulationRequest,
    SimulationResult,
    validate_simulation_request,
    simulate_time_series,
)

from .dataset import (
    SplitName,
    DatasetBuildRequest,
    DatasetSample,
    DatasetBuildResult,
    make_sample_id,
    validate_dataset_build_request,
    build_dataset_in_memory,
)

from .artifacts import (
    ArtifactWriteRequest,
    ArtifactWriteResult,
    validate_artifact_write_request,
    write_dataset_artifacts,
    sha256_file,
)

__all__ = [
    "APPROVED_MAX_P",
    "APPROVED_MAX_Q",
    "APPROVED_MAX_R",
    "APPROVED_MAX_S",
    "SCHEMA_V2_MIN_FLAT_DIM",
    "FamilyId",
    "MeanFamily",
    "VolatilityFamily",
    "ModelSpec",
    "validate_order_bounds",
    "validate_family_consistency",
    "validate_parameter_lengths",
    "validate_no_legacy_collision",
    "validate_model_spec",
    "is_c_family",
    "is_a_family",
    "is_b_family",
    "schema_v2_index_map",
    "to_flat_boundary_vector",
    "from_flat_boundary_vector",
    "VALIDATION_TOLERANCE",
    "PERSISTENCE_TOL",
    "ROOT_BOUNDARY_MARGIN",
    "ConstraintResult",
    "validate_ar_stationarity",
    "validate_ma_invertibility",
    "validate_garch_constraints",
    "validate_math_constraints",
    "require_math_valid",
    "require_constraint_pass",
    "GenerationRequest",
    "GenerationResult",
    "validate_generation_request",
    "generate_model_spec",
    "SimulationRequest",
    "SimulationResult",
    "validate_simulation_request",
    "simulate_time_series",
    "SplitName",
    "DatasetBuildRequest",
    "DatasetSample",
    "DatasetBuildResult",
    "make_sample_id",
    "validate_dataset_build_request",
    "build_dataset_in_memory",
    "ArtifactWriteRequest",
    "ArtifactWriteResult",
    "validate_artifact_write_request",
    "write_dataset_artifacts",
    "sha256_file",
]

