# src/phase2/__init__.py

from .schema import (
    APPROVED_MAX_P,
    APPROVED_MAX_Q,
    APPROVED_MAX_R,
    APPROVED_MAX_S,
    SCHEMA_V2_MIN_FLAT_DIM,
    FamilyId,
    MeanFamily,
    VolatilityFamily,
    ModelSpec,
    validate_order_bounds,
    validate_family_consistency,
    validate_parameter_lengths,
    validate_no_legacy_collision,
    validate_model_spec,
    is_c_family,
    is_a_family,
    is_b_family,
    schema_v2_index_map,
    to_flat_boundary_vector,
    from_flat_boundary_vector,
)

from .constraints import (
    VALIDATION_TOLERANCE,
    PERSISTENCE_TOL,
    ROOT_BOUNDARY_MARGIN,
    ConstraintResult,
    validate_ar_stationarity,
    validate_ma_invertibility,
    validate_garch_constraints,
    validate_math_constraints,
    require_math_valid,
    require_constraint_pass,
)

__all__ = [
    "APPROVED_MAX_P",
    "APPROVED_MAX_Q",
    "APPROVED_MAX_R",
    "APPROVED_MAX_S",
    "SCHEMA_V2_MIN_FLAT_DIM",
    "FamilyId",
    "MeanFamily",
    "VolatilityFamily",
    "ModelSpec",
    "validate_order_bounds",
    "validate_family_consistency",
    "validate_parameter_lengths",
    "validate_no_legacy_collision",
    "validate_model_spec",
    "is_c_family",
    "is_a_family",
    "is_b_family",
    "schema_v2_index_map",
    "to_flat_boundary_vector",
    "from_flat_boundary_vector",
    "VALIDATION_TOLERANCE",
    "PERSISTENCE_TOL",
    "ROOT_BOUNDARY_MARGIN",
    "ConstraintResult",
    "validate_ar_stationarity",
    "validate_ma_invertibility",
    "validate_garch_constraints",
    "validate_math_constraints",
    "require_math_valid",
    "require_constraint_pass",
]
